script:
- set -o pipefail && xcodebuild test -workspace Example/ConcentricProgressRingView.xcworkspace -scheme ConcentricProgressRingView-Example -destination "platform=iOS Simulator,name=iPhone X" | xcpretty
- pod lib lint

language: objective-c
osx_image: xcode9.1
